#MAINYML OF IGP_CENTOS
    - name: Update yum package cache
      yum:
        name: "*"
        state: latest

    - name: Install InfluxDB
      yum:
        name: influxdb
        state: present

    - name: Start and enable InfluxDB service
      systemd:
        name: influxdb
        state: started
        enabled: yes
